pubkey/rxdb

- examples/angular2/README.md
The example requires the adapter-localstorage plugin from the main project. The adapter-localstorage is looking for pouchdb-adapter-leveldb-core and d64 humble-localstorage tiny-queue in it's relative node_modules or any parent directories that have node_modules subdirectory.  Therefore npm install 
(or npm install pouchdb-adapter-leveldb-core d64 humble-localstorage tiny-queue pouchdb-adapter-websql) needs to be run as well.
Additionally, pouchdb-adapter-websql is a dependency of the example, however the dependency graph will continue up into parent directories until it finds a "node_modules/pouchdb-adapter-websql".  Therefore the npm install on the project root will satisfy the dependency.  Alternatively you could go into the lib/adapter-localstorage directory and run npm install
> Update "try it out steps"

- README.md
Just some tiny fixes for spelling issues I found skimming the documentation. 😃
> Minor spelling fixes in Readme

- src/index.d.ts
* Using RxDB in Typescript projects with `noImplicitAny` set to `true` produces compile time warnings.
* For functions that do not specify a return type, I have added an `any` type.
* For lifecycle hooks, I have made the return type `void`, as I could not find any tests or documentation that were using the return value. Please let me know if my assumption was incorrect.
> Make project compatible with "noImplicitAny" Typescript projects

- README.md
Each html block needs a blank line after it preceding nested markdown. Otherwise the markdown is treated as HTML, being part of the block. https://github.github.com/gfm/#html-blocks
> README fixed markdown inside HTML blocks

- docs/LeaderElection.md
Similar to #82 the word 'so' (which should really be 'therefore' or 'then') isn't needed.
> docs LeaderElection reword

- docs/DataMigration.md
'compareable' is not a word and 'comparable' doesn't have the right meaning
> docs DataMigration typo reword

- src/index.d.ts
export PouchDB for check adapter can use.
const db = new PouchDB('mydb', { adapter: adapter });
return db.info();
> improve index.d.ts

- test/unit/PouchDB-integration.test.js
Microsoft Edge, just like Internet Explorer [does *not* support websql](http://caniuse.com/#feat=sql-storage). Tests fail on MS Edge when importing `pouchdb-adapter-websql`.
Here's the stack trace for the offending test:
```
Edge 14.14393.0 (Windows 10 0.0.0) PouchDB-integration.test.js websql positive should work after adding the adapter FAILED
Error: Adapter websql not added.
Use RxDB.plugin(require('pouchdb-adapter-websql');
at _callee9$ (C:/Users/Jacek/AppData/Local/Temp/9bb33e79b3ffd33b7098ebe86521016c.browserify:3499:25)
at tryCatch (C:/Users/Jacek/AppData/Local/Temp/9bb33e79b3ffd33b7098ebe86521016c.browserify:213390:7)
at invoke (C:/Users/Jacek/AppData/Local/Temp/9bb33e79b3ffd33b7098ebe86521016c.browserify:213625:9)
at prototype[method] …
```
> Disables pouchdb-adapter-websql tests in Edge

- package.json
- src/mquery/mquery.js
- src/mquery/mquery_utils.js
The included mquery library uses a non-standard export syntax. This makes webpack unable to transpile it in the angular2 build process. This PR updates the mquery exports.
With this fixed, angular2 will use the RxDB source files, transpile them in it's own build process, and will not require the babel-polyfill.
Additionally, I've added a `module` field to package.json, as [webpack 2.x doesn't use the provided `jsnext:main` field by default](https://webpack.js.org/configuration/resolve/#resolve-mainfields).
If this is merged, I'll update the included angular2 example.
BTW, I wasn't able to reliably run the tests - they seem to sometimes fail randomly for no apparent reason (I did manage to get 100% passes at least once ;) ).
> Refactor mquery to use ES6 module syntax and enable usage of the untranspiled source as a module

- examples/angular2/app/polyfills.ts
- examples/angular2/package.json
The RxDB source can now be used as a module directly in Angular, without the need to use the transpiled library from the `dist` folder. This makes `babel-polyfill` no longer required by the example, as the provided core.js polyfills are sufficient.
This PR removes `babel-polyfill` from the example.
> Remove babel-polyfill from the Angular example

- src/index.d.ts
So I am not 100% sure about this one, so it comes as a separate pull request.  Problem: 
```js
db.collection({
name: 'accounts',
schema: {
title: 'accounts schema',
version: 0,
type: 'object',
properties: {
name: {
type: 'string',
primary: true
},
type: {
type: 'string'
},
banking: {
type: 'object'
}
}
}
});
```
is not valid, due to properties being set to type `JsonSchema`, which requires `type` to be a string.
I think the change in the pull request would not be correct if `schema.type` is set to s.th. like `string`, but must use-cases are probably `object`, for which properties is a key-schema map.
I might have not actually created this pull request if the invalid field was just `type`, but with properties set to `JsonSchema` the problem occurs also with other fields in `JsonSchema`, …
> fix typings of SchemaJSON#properties

- src/index.d.ts
Allows usage of TypeScript compiler flag "noImplicitAny", this was the only place no explicit return type was provided for a function.
> Added explicit any return for PouchDB info

- package.json
- src/RxCollection.js
- src/RxDocument.js
- src/RxQuery.js
- test/unit/RxCollection.test.js
- test/unit/RxDocument.test.js
Reverts pubkey/rxdb#153
Test not working:
```js
it('unset a value', async() => {
const c = await humansCollection.createPrimary(1);
const query = c.find();
await query.update({
$unset: {
firstName: ''
}
});
const docs = await query.exec();
for (let doc of docs)
assert.equal(doc._data.firstName, undefined);
c.database.destroy();
});
```
> Revert "added update functionality"

- src/RxCollection.js
This allows me to implement query based sync until its more officially supported.
> Split out watchForChanges to support external replications

- src/index.d.ts
In typescript declaration, leave it to typescript/webpack compiler and not forcefully polyfill `Promise`. Project not using `es6-promise` polyfill experiences typing error, having two mis-matched versions of `Promise`.
Fixed an argument declaration.
> Typescript fix

- src/index.d.ts
Improved Typings
Development with strong types is easier when all the used interfaces are available to the developer. 
For instance, look at this file I wrote for one of my collections:
```ts
import { RxCollectionCreator, RxSchema } from 'rxdb';
export interface IExpenseType {
id?: string;
name?: string;
}
export const ExpenseTypeSchema = {
type: 'object',
version: 0,
disableKeyCompression: true,
properties: {
id: {
type: 'string',
primary: true
},
name: {
type: 'string'
}
}
};
export const ExpenseTypeCollection: RxCollectionCreator = {
name: 'expense-type',
schema: RxSchema.create(ExpenseTypeSchema)
};
```
If I had access to the `SchemaJSON` interface, I would be able to assign it as a type for `ExpenseTypeSchema`. This will make my IDE let me know as soon as I've made a mistake and …
> Export all interfaces

- docs-src/rx-collection.md
Using hyphenated values often suggests proper nouns. By removing extra hyphens, the subject and object are properly separated.
> Minor grammatical cleanup.

- docs-src/rx-attachment.md
according to https://github.com/pubkey/rxdb/blob/master/src/plugins/attachments.js#L161-L165 we need to use an object here
> doc: fix putAttachment example

- docs-src/rx-collection.md
Improved docs
Further clarification on collection select in docs. Mentioned it on Gitter, fixed here: https://github.com/pubkey/rxdb/commit/01b8e9fd6d6a5e8c266ffd1154a59f57fd0e4db0
Code just underneath `Get a collection from the database` might suggest that first line is a way to get collection, not create it. It looked like two alternative methods for accessing collection. Might be to specific though, leaving decision to maintainer.
> Update docs - clarify collection selection from database.

- package.json
Since babel-polyfill isn't always needed, it shouldn't be listed in the peerDependencies.
> Remove babel-polyfill from peerDependencies

- src/typings/rx-collection.d.ts
- src/typings/rx-query.d.ts
RxQuery must differ between model and result to get typeof working. And `where` also allows a key from the model.
> Fix TypeScript Definitions for RxQuery

- docs-src/rx-schema.md
Improved docs
Follow up on https://github.com/pubkey/rxdb/pull/438
Added info in docs about fields types working with `index`
> Update docs - add information about index and allowed field types.

- package.json
- A BUGFIX
The preinstall script assume that all dev got the rm commands on their system
But on the cmd, rm does not exist
In powershell the rm command exist but not the -f arguments
https://github.com/pubkey/rxdb/issues/558
> Removing the preinstall script to support windows shells

- src/rx-database.js
- src/typings/pouch.d.ts
- src/typings/rx-database.d.ts
- test/unit/rx-database.test.js
- A BUGFIX
When using 'cordova-sqlite' adapter (which uses native Cordova SQLite as its backing store) we need RxDB to create an instance of PouchDb with specified **location** or **iosDatabaseLocation** (these are required by cordoa sqlite plugin).
So an instance of PouchDb should be created like this:
```
new PouchDB('dbname', {adapter: 'cordova-sqlite', location: 'default'})
```
or this
```
new PouchDB('dbname', {adapter: 'cordova-sqlite', iosDatabaseLocation: 'default'})
```
The current implementation of RxDB let us specify only adapter.
This PR will give the possibility to specify location or iosDatabaseLocation in options property when creating database
```
await RxDB.create({
name: 'dbname',
adapter: 'cordova-sqlite',
password: 'passwordPasswordPassword',
options: { location: …
```
> Add support to specify location and iosDatabaseLocation

- src/typings/rx-change-event.d.ts
This contains some improvements to the RxChangeEvent typing for things that were missed in https://github.com/pubkey/rxdb/pull/606
* Use a named type for the operation strings.
* Allow the type of the `v` object to be defined, optionally.
* `doc` is a string (the primary key), not a document.
> Improve RxChangeEvent typing

- docs-src/rx-collection.md
- find by using sql equivalent '%like%' syntax
- find using a composite statement eg: $or
- do a case insensitive search
> some advanced query examples

- docs-src/in-memory.md
- docs-src/replication.md
> Improve docs

- config/karma.conf.js
- package.json
- Prevents Chrome Canary from being run in tests -as the browser itself is unstable, like Firefox nightly.
- Adds karma-safari-launcher to devDependencies & karma loaded plugins so tests run in macOS.
> Safari launcher

- dist/lib/plugins/replication.js
- docs-src/replication.md
- src/plugins/replication.js
- test/unit/replication.test.js
> Replication alive$

- docs-src/tutorials/typescript.md
- Improved docs
- Tutorial "Using RxDB with Typescript" incorrect `RxCollection` type definition.
The documentation tutorial page "Using RxDB with Typescript" defines `HeroCollection` incorrectly as `RxCollection<HeroDocType, HeroDocMethods>` when it should be defined as `RxCollection<HeroDocType, HeroDocMethods, HeroCollectionMethods>` to provide typing for the static methods.
> Tutorial "Using RxDB with Typescript" incorrect RxCollection type definition.

- docs-src/install.md
> Fix variable capitalisation in install docs

- src/rx-database.js
There was a `Promise.all` that was not being awaited.
I don't know if the ordering is important.
e.g. that the collections are destroyed before the internal admin/collections collection.
However it should be awaited somehow so that `removeDatabase` doesn't return before the `.destroy()` calls have finished.
> Awaits Promise.all in RxDB.removeDatabase

- docs-src/install.md
The closing ')' in the Wikipedia link broke the Markdown rendered on the docs site (not inside GitHub).
Also, a minor grammar tweak.
Minor doc issues.
> Markdown formatting fix.

- CHANGELOG.md
- docs-src/tutorials/typescript.md
- package.json
- test/helper/schemas.js
- test/typings.test.js
- typings/rx-schema.d.ts
Make RxJsonSchema optionally generic to have type checking on `properties` and `required`.
> ADD RxJsonSchema generic

- CHANGELOG.md
- src/rx-database.js
- test/unit/reactive-database.test.js
- A Bugfix
While creating a collection, a subscriber to the db is notified of that, but cannot access the collection via the db object, since it is added after the emitting process.
> Emit collection change after adding it to the db object

- docs-src/install.md
`require` statement is a `CommonJS` statement and not a `ES5` statement.
- [ x ] Documentation
> Replace `es5` with `CommonJS` in comments

- CHANGELOG.md
- docs-src/custom-build.md
- package.json
- plugins/validate-z-schema/index.d.ts
- plugins/validate-z-schema/package.json
- src/plugins/validate-z-schema.js
- test/unit/plugin.test.js
- test/unit/validate-z-schema.node.js
Both `is-my-json-valid` and `ajv-validate` use `eval()` to perform validation which might not be wanted when `'unsafe-eval'` is not allowed in Content Security Policies. This one is using [z-schema](https://github.com/zaggino/z-schema) as validator which doesn't use `eval`.
Related to #243, actually closes #235
> ADD z-schema validator plugin

- typings/rx-document.d.ts
`getAttachment` returns `null` when the requested attachment does not exist. 
Reflect this in the typings so that clients know to handle the `null` case.
I was using `getAttachment` with the assumption that it would return something. This is not always the case, however, so it could throw a runtime error.
> `getAttachment` type should be nullable

- src/rx-document.js
- SOMETHING ELSE
I consider this not really as bug, its more a kind of exception improvement.
In the below exception the information of old and new values are interchanged 
`RxError: RxError:
final fields cannot be modified
Given parameters: {
dataBefore:{
"_rev": "1-5bf10021913fa326879ebf447d18cca5",
"key": "new value"
}
dataAfter:{
"_rev": "1-5bf10021913fa326879ebf447d18cca5",
"key": "old value"
}
fieldName:"key"}`
this is because validateChange of rx-schema expects the old data as first argument and the new one as second but is called as follows:
`rx-document: this.collection.schema.validateChange(newData, oldData)`
`rx-schema: function validateChange(dataBefore, dataAfter)`
> switched params of schema validation call

- src/types/rx-plugin.ts
fix #1533 
When creating a plugin using typescript, the `hooks` property doesn't contain the type for `preCreateRxCollection` function.
> add preCreateRxCollection

- docs-src/adapters.md
Using `IndexedDB` capitalisation consistent with [MDN](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)
- Improved Docs
> Adapters.md – Fix typo & consistent IndexedDB

- CHANGELOG.md
- src/plugins/server.ts
- test/helper/schema-objects.ts
- test/unit/server.test.ts
A fix for serving migrated schemas with the server plugin.
When using rxdb, I have a version 1 schema, and it doesn't sync new data from the server since it only finds the v0 database for the collection.
> Fix serving migrated collections with server plugin

- .travis.yml
- examples/electron-remote/.gitignore
- examples/electron-remote/.npmrc
- examples/electron-remote/README.md
- examples/electron-remote/database.js
- examples/electron-remote/index.html
- examples/electron-remote/main.js
- examples/electron-remote/package.json
- examples/electron-remote/page.js
- examples/electron-remote/style.css
- examples/electron-remote/test/render.test.js
- examples/electron-remote/test/spec.js
- examples/electron/README.md
- NEW EXAMPLE
None.
This is another example of implementing RxDB with Electron but using `remote` instead of `RxDB server plugin`.
> Create a new example with Electron remote

- docs-src/plugins.md
- Fixed outdated links in docs
There are some links on the "plugins" page of the docs that link to `.js` files which have been changed to `.ts` files. I have changed the destination of those links in the `docs-src/plugins.md` file.
The outdated links can be seen on the live [plugins][plugins] page under the "prototypes", "hooks", and "overwriteable" headers.
[plugins]: https://rxdb.info/plugins.html
> update links in plugins docs

- docs-src/tutorials/typescript.md
- src/types/rx-document.ts
- Updated docs
I noticed that the `document.collection` property isn't typed with the collection's static methods. This updates the types so the collection static methods can be added when setting up the document's type.
I've also updated and rearranged the docs for types so it makes more sense- you can't send the collection methods in to the document type if you haven't declared them yet.
I set a default for the collection method types, so this is not a breaking change.
> Add collection methods to document type

- src/plugins/server.ts
I am wanting to use rxdb with pouchdb-auth, to provide user authentication, but I am unable to define an admin user at first startup.
This is because pouchdb-auth requires them to be defined as part of its config, which is only exposed on the pouchApp object this exposes. If an admin user is not defined, then every client will be an admin, so not having this control makes securing the master database on first startup very hard.
An example of how the result of this can be used for this is:
```
pouchApp.couchConfig.set('admins', 'admin1', 'password', cb);
```
There was some other fiddling I need to do with raw PouchDB databases to get the client side rxdb setup with pouchdb-auth, but that is fine. (I think just configuring pouchdb-auth with the special _users database)
> feat: expose pouchApp from spawnServer

- docs-src/replication-graphql.md
- src/plugins/replication-graphql/index.ts
- src/types/plugins/replication-graphql.d.ts
- test/unit/replication-graphql.test.ts
A New Feature
I am using graphql replication. In my use case, in my query builder I need to run asynchronous operations before returning the query and variables. 
I have included a new unit test that simply wraps the existing test queryBuilder in an async function. Additionally all the existing tests still pass.
> Allow query builders to be asynchronous

- src/rx-storage-pouchdb.ts
- test/unit/bug-report.test.ts
- A BUGFIX
In `rx-storage-pouchdb.prepareQuery`, a `gt` operator in selector is added if not already present.
This creates a problem if the selector originally has `gte` operator as `pouch-find` internally merges startKey for both these operators, mostly overriding gte with gt.
This PR checks for any comparison operators in selector for that key, and adds that hack only if required, and thereby avoiding reproduced issue.
> bugfix in prepareQuery for pouchdb

- docs-src/population.md
- src/plugins/dev-mode/check-schema.ts
- src/plugins/dev-mode/error-messages.ts
- test/unit/population.test.ts
Cannot define a relation property in an RxSchema with a nullable string, as a type of ['string', 'null'] is not accepted. But without a null-type, any validation of objects with a null-reference will fail because they don't fit the schema.
Discussed in issue #2285 .
> Nullable relation in RxSchema

- CHANGELOG.md
- src/plugins/replication-graphql/helper.ts
- src/plugins/replication-graphql/index.ts
- src/types/plugins/replication-graphql.d.ts
GraphQL replication async modifier function
Implementation for - #2367 
Existing tests seem to be adequate to check that this hasn't caused any regressions.
> feat: GraphQL replication async modifier function

- docs-src/replication-graphql.md
- src/plugins/replication-graphql/index.ts
- test/helper/graphql-server.ts
- test/unit/replication-graphql.test.ts
Headers of the GqlReplState cannot be changed currently, e.g. when Authentication Tokens change.
#2389
> Setter for Headers of GraphQlReplicationState 

- src/rx-collection.ts
- src/util.ts
- test/helper/humans-collection.ts
- test/helper/schema-objects.ts
- test/helper/schemas.ts
- test/unit/rx-collection.test.ts
- test/unit/rx-query.test.ts
A bugfix concerning compound indexes
I tried to create a _compound index_ (age + id) that contains the primary key (id) of the schema and sort docs by the attributes of the compound index (see test). This fails with the error message "_cannot sort on field(s) 'age' when using the default index_". Why is the default index ('_id)' used here, although an appropriate custom index has been defined?
The first problem was that in _RxStoragePouchDbClass_ - **prepareQuery()** the primary key is changed to '_id' and therefore the new custom index does not match the attribute anymore: 
https://github.com/pubkey/rxdb/blob/8b954b44ce67177003d2ceef2d79c54bc1d27c23/src/rx-storage-pouchdb.ts#L221
Therefore in my opinion the method **createIndex()** of _RxCollection_ has to be adapted and the change of …
> Create compound index with primary key and sort by its items 

- README.md
- docs-src/tutorials/typescript.md
This PR updates the readme and docs to mention that RxDB v9 requires Typescript v3.8 or higher. Issue was raised in #2487
> Update the readme and docs to mention minimum version of Typescript required

- src/plugins/replication-graphql/index.ts
An optimization
(as discussed on gitter)
GQL replication was acting slower than expected - on inspection saw there was a `bulkDocs` operation per doc, per batch but this can be reduced to a single `bulkDocs` operation per batch, resulting in faster replication.
Existing tests are passing. Let me know if the PR needs anything else.
> Rework gql replication pull to write docs in single db operation

- docs-src/replication-graphql.md
Improved docs.
The current GraphQL replication docs use wrong names of the params.
https://github.com/pubkey/rxdb/blob/996b5bbb13b41dba14d00f3b3bad6ad78bc26450/src/types/plugins/replication-graphql.d.ts#L13-L21
> In GraphQL replication docs use the correct names of the input params

- docs-src/rx-schema.md
New to RxDB / Pouch / Couch. Spent a few hours evaluating security considerations across each for an upcoming project. Password use for encryption isn't very clear in the schema section of the current docs.
This commit provides a brief description and link to the relevant section in the database creation doc (which I stumbled across after the fact).
Couldn't work out how encryption worked from the docs alone.
> docs: explain password use in schema > encryption

- examples/react/src/Database.jsx
- A BUGFIX
Sorry I forgot another import in the react example. Travis should pass after the change.
> FIX add RxDBNoValidatePlugin to react-example

- src/plugins/replication-graphql/index.ts
- test/unit/replication-graphql.test.ts
When updating the rxdb package after the latest release and trying out the feature in our code base, we've noticed that a small bug has remained that . We are yet unsure why this bug wasn't caught by the tests that had been defined for the previous PR.
> FIX skipping docs in push replication

- test/helper/schema-objects.ts
- test/unit/rx-collection.test.ts
This PR replaces use of `randomInt` with`randomNumber` (from pubkey's `async-test-util` library) in test files that can make use of `async-test-util`. Motivation comes from a TODO comment in `test/helper/schema-objects.ts`.
Original TODO comment:
```
// TODO replace these 2 with methods of async-test-util
import randomToken from 'random-token';
import randomInt from 'random-int';
```
There is one other file that uses `random-int`, but for now I'll hold off on replacing it as it can't make use of `async-test-util` (thank you @dome4).
> Replace randomInt with randomNumber from async-test-util in test files

- src/plugins/replication-graphql/index.ts
- test/unit/replication-graphql.test.ts
-  IMPROVED TESTS
- A BUGFIX
I experienced that `awaitInitialReplication()` of the graphql replicator plugin resolves even if the replication never succeeds (see attached issue). Is this the expected behavior? 
`syncGraphQL()` executes `replication.run()` ([see code](https://github.com/pubkey/rxdb/blob/88a99ed9eab7cdac4af6abf003aa307c20da9909/src/plugins/replication-graphql/index.ts#L518)) without param and thus the default `retryOnFail = true` is used. If this first pull cycle fails `run()` is executed with the default param again ([code](https://github.com/pubkey/rxdb/blob/88a99ed9eab7cdac4af6abf003aa307c20da9909/src/plugins/replication-graphql/index.ts#L193)). Works as expected.
The problem is that `syncGraphQL` executes `run(false)` on every following pull sync cycle every …
> graphql - await initial replication resolves on failed replication

- docs-src/SUMMARY.md
- docs-src/rx-collection.md
- src/rx-collection.ts
- test/unit/hooks.test.ts
- test/unit/reactive-collection.test.ts
- test/unit/rx-collection.test.ts
> Feat RxCollection support bulkRemove

- src/types/rx-collection.d.ts
- src/types/rx-database.d.ts
- test/typings.test.ts
The typing of `insertLocal` in `rx-database.d.ts` and `rx-collection.d.ts` was the following:
```
insertLocal<LocalDocType = any>(id: string, data: any): Promise<...>;
```
I haven't discovered any reason, why data should not be typed with the `LocalDocType` as `upsertLocal()` does it too.
There was also some code redundancy between `rx-database.d.ts` and `rx-collection.d.ts`, which was resolved as well.
A typing test was added accordingly.
> Enhance local document types

- examples/graphql/README.md
- examples/graphql/client/index.html
- better GraphQL example instructions
- Fix a copy/paste error in the GraphQL example
The GraphQL example will not install with the current instructions, which not follow the pattern of the other examples (which work). The example page shows "Vanilla" when it is for the `graphql` example
> Fix GraphQL example install docs and bad cp/paste

- docs-src/rx-collection.md
Notice on `findByIds` behaviour in the documentation
It is unclear from the docs whether `findByIds` will populate the `Map` in the same order as that of the ids passed for filling it. It does not in all cases, though might be expected to by some users, so a warning is warranted.
> Add notice findByIds doesn't respect input order

- docs-src/rx-collection.md
logically I think it should have been an 'an' instead of 'and'
- Improved Docs (Typo)
Just a small typo.
> Typo in findbyIds$()

- examples/graphql/package.json
A fix to the `start` script of the graphql example.
Without this PR the client part of the graphql example does not start (see log below).
Error and solution applied:
https://stackoverflow.com/a/64205610/1850609
Commit that updated webpack:
https://github.com/pubkey/rxdb/commit/d199b9c8f0b13695d4f466cfa2f9a6c275da822a#diff-192ef64589816349604beb98f7a1f5d3d8a5f4b61484f796a8e2a013dcf76da2
Error log (without the fix):
```
$ npm start
> rxdb-example-graphql@ start ~/rxdb/examples/graphql
> concurrently "npm run server" "npm run dev"
[0] 
[0] > rxdb-example-graphql@ server ~/rxdb/examples/graphql
[0] > node -r esm ./server/index.js
[0]
[1]
[1] > rxdb-example-graphql@ dev ~/rxdb/examples/graphql
[1] > webpack-dev-server
[1]
[1] internal/modules/cjs/loader.js:628
throw err;
[1]     ^
[1]
[1] …
```
> fix(examples/graphql): update webpack start command

- docs-src/replication-graphql.md
on GraphQL push replication docs.
closes #3144
graphQL replication example is missing `deleted` field that is specified as `deletedFlag`
> add missing `deleted` field

- src/types/rx-database.d.ts
- test/typings.test.ts
- test/unit/local-documents.test.ts
getLocal looks like it always returns a doc, but can return `null` if they key does not exist.
> add missing possible `null` for `getLocal` on database

- src/core.ts
Types for `MigrationStrategy` are not available
> add missing migration types to export

- CHANGELOG.md
- src/plugins/server.ts
- src/util.ts
- test/unit/server.test.ts
- A BUGFIX
When full leveldown-module is passed to `getRxStoragePouch`, [spawning a server](https://rxdb.info/rx-database.html#server) throws the following error:
```
Error: Invalid Adapter: function LevelDOWN (location) {
if (!(this instanceof LevelDOWN)) {
return new LevelDOWN(location)
}
if (typeof location !== 'string') {
throw new Error('constructor requires a location string argument')
}
AbstractLevelDOWN.call(this, {
bufferKeys: true,
snapshots: true,
permanence: true,
seek: true,
clear: true,
createIfMissing: true,
errorIfExists: true,
additionalMethods: {
approximateSize: true,
compactRange: true
}
})
this.location = location
this.context = binding.db_init()
}
at PouchAlt.PouchDB (/home/runner/work/rxdb/rxdb/node_modules/pouchdb-core/lib/index.js:1292:11)
at new PouchAlt …
```
> Fix an error on server spawn when full leveldown-module is used

- src/plugins/pouchdb/custom-events-plugin.ts
Fix of [[custom-events-plugin] - Cannot read 'ids' of undefined](https://github.com/pubkey/rxdb/issues/3520)
> Quick fix for https://github.com/pubkey/rxdb/issues/3520

- babel.config.js
- orga/performance-trackings.md
- package.json
- src/plugins/lokijs/loki-save-queue.ts
- src/plugins/lokijs/lokijs-helper.ts
- src/plugins/lokijs/rx-storage-instance-loki.ts
- src/plugins/lokijs/rx-storage-key-object-instance-loki.ts
- src/plugins/lokijs/rx-storage-lokijs.ts
- src/plugins/worker/workers/tsconfig.json
- src/plugins/worker/workers/webpack.config.js
- test/unit/rx-storage-implementations.test.ts
- test/unit/rx-storage-lokijs.test.ts
- tsconfig.json
Work in progress.
I found out that transpiling async/await to promises instead of generators, we can save about 10% of bundle size. Also the performance improved. https://www.npmjs.com/package/babel-plugin-transform-async-to-promises
Currently waiting for a fix of this bug: https://github.com/rpetrich/babel-plugin-transform-async-to-promises/issues/62
> WIP transpile to promises instead of generators

- examples/angular/README.md
- examples/electron/README.md
- examples/graphql/README.md
- examples/react/README.md
- examples/svelte/README.md
npm apparently removed this getting done automatically, so it needs to
be executed manually for the examples to work.
The examples do not run with the existing documentation instructions in the README.mds
- [x ] Documentation
> Update example readmes to include preinstall

- src/plugins/dev-mode/check-schema.ts
- src/plugins/key-compression.ts
- src/plugins/lokijs/rx-storage-instance-loki.ts
- src/plugins/pouchdb/rx-storage-pouchdb.ts
- src/rx-schema.ts
- src/types/rx-error.d.ts
- src/types/rx-schema.d.ts
- src/types/util.d.ts
- src/util.ts
- A BUGFIX
Following "Option A" for typing for providing a schema and generating the doc type in TypeScript from the [Use RxDB with Typescript guide](https://rxdb.info/tutorials/typescript.html), I tried to add a composite index to the hero example with something like:
```ts
indexes: ['firstName', ['lastName', 'passportId']]
```
As far as I can tell, that syntax should be okay. I consulted the [RxSchema docs](https://rxdb.info/rx-schema.html#indexes) to be sure. However, making that change causes a TypeScript compilation failure when using the `RxJsonSchema` type. Using the "hero" example from the aforementioned TypeScript guide:
```ts
const heroSchema: RxJsonSchema<HeroDocType> = heroSchemaLiteral;
```
I end up with the following compilation error:
```
Types of …
```
> Support composite indices in schema literal types

- src/plugins/replication-graphql/crawling-checkpoint.ts
- src/plugins/replication-graphql/index.ts
- src/plugins/replication/index.ts
- src/plugins/replication/replication-checkpoint.ts
- test/unit/replication-graphql.test.ts
- test/unit/replication.test.ts
- A bugfix
I was working on a project using GraphQL replication without subscriptions and I left a browser tab open for an ungodly amount of time. To my surprise, my local storage had gotten bloated to the point where I couldn't access it anymore. While investigating I noticed that thousands of `push-checkpoints` were being created.
Indeed, I was able to confirm that a new push-checkpoint was made on every sync operation. @pubkey confirmed in Gitter [that this is indeed a bug](https://gitter.im/pubkey/rxdb?at=61e37eaf526fb77b317feec2).
My solution is to surround the `setLastPushSequence` with the same check that is in the `catch` block above. This works well in my testing. I'll note that this **doesn't technically solve the memory leak** and is only kicking it down the road to when …
> [GraphQL Replication] Only create a new push sequence if necessary

- docs-src/replication-graphql.md
- src/plugins/lokijs/lokijs-helper.ts
- src/plugins/replication-graphql/index.ts
- test/helper/graphql-server.ts
- test/helper/schema-objects.ts
- test/helper/schemas.ts
- test/unit/replication-graphql.test.ts
- A BUGFIX
I'm replicating from a GraphQL store in front of a PostgreSQL database. Handling soft deletion in relational databases by storing a `deletedAt`|`deleted_at` timestamp column rather than a boolean flag is a common practice.  While I could wrap the whole thing with a view to expose a boolean flag, it would be handy if I could use this timestamp directly.
I thought maybe RxDB handled truthy values for the `deletedFlag` by default. This seemed to work fine with PouchDB, but when I tried LokiJS, I ran into a confusing problem. When data was pulled from the GraphQL service, it would show in the web app immediately. But, when the web app was reloaded, the data wouldn't show. I tracked that down to queries having the `where('_deleted').eq(false)` …
> Allow truthy values for the GraphQL replication `deletedFlag` field.

- docs-src/custom-build.md
In docs: 
```js
import { RxDBReplicationCouchDBPlugin } from 'rxdb/plugins/replication';
addRxPlugin(RxDBReplicationCouchDBPlugin);
``` 
but the right path shold be: `'rxdb/plugins/replication-couchdb'`
> fix: import path of RxDBReplicationCouchDBPlugin in documentation

- docs-src/replication-graphql.md
- src/plugins/replication-graphql/index.ts
- src/plugins/replication/index.ts
- test/unit/replication-graphql.test.ts
This PR is a proposed solution to #3622. Errors encountered during GraphQL replication are wrapped in a new `ReplicationError` object that records whether it was a pull or push replication that failed, and if a push failure, the associated document data in the failed request.
For the time being, I've only applied these changes to GraphQL replication, although I think it could be handled for all forms of replication. There were a variety of design decisions made in getting this far and I'm happy to adjust as necessary. I just wanted to get something functional that could then be evaluated. Some areas that would be helpful to get feedback on are:
* Should the replication error payload be a discriminated union or just fields in the class? I went with the discriminated union …
> Record details about replication action and associated document, if any, upon replication failure.

- src/plugins/replication/index.ts
- src/util.ts
- test/unit/replication-graphql.test.ts
- test/unit/replication.test.ts
- test/unit/util.test.ts
- A BUGFIX
Actual:
- no push on document updates if live=false
- no way to disable polling: liveInterval=0 is rejected by ensureNotFalsy() line 581 when live=true
Expected:
- do not poll if liveInterval=0 and live=true
- push triggered on document updates
> fix behaviour to fit with documentation in back channel use.

- docs-src/replication.md
- src/plugins/replication-graphql/index.ts
- src/plugins/replication/index.ts
- src/types/plugins/replication-graphql.d.ts
- src/types/plugins/replication.d.ts
- test/unit/replication.test.ts
- A NEW FEATURE PROPOSAL
`replicateRxCollection()` provides a way to configure the way to replicate a given collection.
However, by default, this function also run an initial replication as side effect.
IMHO, it's a matter of separation of concerns:
The moment to configure collections and replications is not always the same we get ready to do the first replication.
I would like to trigger replications collection by collection and keep control on the order, the timing... and separately from the replication definition.
I suggest to add an option to prevent the default first replication and separate the replication configuration and triggering.
This PR adds new option `runInitialReplication`.
It could be set to false to avoid  `initialReplication` on `replicateRxCollection()`.
default to …
>  add new option autoStart.

- examples/node/src/database.js
- A BUGFIX
In Node example, this pr fix  the following error:
_Error: You are using a function which must be overwritten by a plugin.
You should either prevent the usage of this function or add the plugin via:
import { RxDBQueryBuilderPlugin } from 'rxdb/plugins/query-builder';
addRxPlugin(RxDBQueryBuilderPlugin);_
> Fix Node example

- src/types/rx-query.d.ts
fix types for `nor` and `and` query
According to the [query doc](https://github.com/aheckmann/mquery/blob/master/README.md#and), `and` and `nor` methods accept an array of query filters. Without this PR I need to do `query.and([] as any)`
> fix: typings

- docs-src/replication-graphql.md
I'm pretty sure, that it has to be the id of the document instead of the name 🙂
> FIX(docs) change field value for lastId

- src/rx-query.ts
I'm pretty sure this type is incorrect. It should be an array of documents.
> bug in query results type

- src/types/rx-schema.d.ts
- test/unit/validate.test.ts
Fixed types for `additionalProperties` with a corresponding tests
Unable to use a json schema for nested `additionalProperties`
> Support JsonSchema for nested additionalProperties

- examples/angular/src/app/schemas/hero.schema.ts
- examples/angular/src/app/services/database.service.ts
This fix 2 issues that were making angular example not working:
* missing `maxLength` in schema
* wrong object passed to `addRxPlugin` function
> Fix angular example

- docs-src/replication-graphql.md
- src/plugins/replication-graphql/index.ts
- src/types/plugins/replication-graphql.d.ts
- test/unit/replication-graphql.test.ts
This is a feature for https://github.com/pubkey/rxdb/issues/3439
This Pull Request adds the option to pass the credential parameter to the underlying GraphQL client. Without it the application will not send any cookies to other domains since the credentials option is `same-origin` per default. See the spec documentation at https://fetch.spec.whatwg.org/#concept-request-credentials-mode
> How should I update the changelog?
> feat: include crededentials in graphql client

- CHANGELOG.md
- docs-src/replication-graphql.md
- src/index.ts
- src/plugins/replication-graphql/index.ts
- src/plugins/replication/index.ts
- src/types/plugins/replication-graphql.d.ts
- src/types/plugins/replication.d.ts
- test/unit/replication-graphql.test.ts
WORK IN PROGRESS
ADD `pull.responseModifier` to the graphql replication plugin so that you can aggregate the checkpoint from the returned graphql respones.
> CHORE graphql pull.responseModifier

- docs-src/replication.md
A fix for a typo in the docs.
The word "and" was used instead of the correct "an".
> fix typo on replication.md

- src/util.ts
- test/unit/rx-collection.test.ts
- test/unit/rx-storage-implementations.test.ts
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#access_an_array_item_by_its_index
> may return undefined if `array`  is empty

- dist/types/plugins/pouchdb/pouchdb-helper.d.ts
I'm facing build issue when using RxDB from Angular project due to triple-slash directive usage in `pouchdb-helper.d.ts`.
Minimal project to reproduce issue
* `packages.json`
```json
{
"dependencies": {
"rxdb": "^13.4.5"
}
}
```
* `main.ts`
```typescript
import { addPouchPlugin, getRxStoragePouch } from 'rxdb/plugins/pouchdb'
console.log("Hello world")
```
* `tsconfig`
```json
{
"compilerOptions": {
"types": []
}
}
```
Build command line
```bash
npm i && tsc
```
Build error
```
...
node_modules/@types/node/ts4.8/buffer.d.ts:97:14 - error TS2661: Cannot export 'Buffer'. Only local declarations can be exported from a module.
97     export { Buffer };
~~~~~~
Found 1 error in node_modules/@types/node/ts4.8/buffer.d.ts:97
```
> Remove legacy triple slash directives

- docs-src/replication.md
This one is a little tricky. The original sentence with just a comma (,) delimiter reads like a run-on sentence. I tried replacing it with a period/full-stop (.) to make two sentences, but I think that loses some of the impact the original version intended. A semi-colon (;) strikes me as being appropriate because the second part really builds on the first part, but needs a stronger separator than a comma. While I think it works here, the semi-colon is fairly niche use in most English writing. Other options that I think could work in place of the semi-colon would be a colon (:) or mdash (—).
> TYPOFIX: Fix a run-on sentence.

- src/plugins/replication/index.ts
- test/unit/replication-graphql.test.ts
* A bugfix
At this time it doesn't appear to be possible to stop RxDB from retrying requests after a non-recoverable error (ex 401). A simple example:
```typescript
const state = db.test.syncGraphQL({
url: { http: "/badurl" },
pull: {
queryBuilder: pullQueryBuilderFromRxSchema("test", {
schema: schema,
checkpointFields: ["id", "updatedAt"],
}),
},
live: false,
});
state.error$.subscribe((err) => {
console.log("error", err);
void state
.cancel()
.catch((err) => console.log("cancel error", err))
.then(() => console.log("cancel done"));
});
```
"Cancel done" is logged to the console however a new request is still sent every 5 seconds.
> Stop retries

- dist/types/plugins/crdt/index.d.ts
- src/plugins/crdt/index.ts
- test/unit/crdt.test.ts
- A BREAKING CHANGE, a plugin typo
All plugin have RxDB as a prefix, CRDT plugin did not have it. Also, if you want to merge it, it will probably better to fix the lowercase crtd to all uppercase since its an abbreviation.
> Typo in CRDT Plugin: RxDDcrdtPlugin

- src/types/plugins/replication.d.ts
- IMPROVED typings (doc)
- Wrong interface info on replication types. `autoStart` and `live` had outdated info. `Live` default value changed. I used the documentation available [here](https://rxdb.info/replication.html)
> Updated Replication interface doc to v13 changes

- src/replication-protocol/downstream.ts
- test/unit/replication.test.ts
It seems that the fix for #4117 in #4124 was not complete. However, the provided test case wasn't complete either.
I've extend the test case to also test if `false` is emitted after replication has completed.
> fix: emit false on active$ after replication is done

- package.json
This PR fixes the issue on some javascript environments (Sveltekit) when you get a resolution error for plugins dependencies as
```
Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import 'C:\Users\SebasG\Documents\svelte-kit-demo\node_modules\rxdb\plugins\query-builder' is not supported resolving ES modules
```
Adding entries to the package JSON to ensure the validation works correctly. 
After this PR is merged we can add a sveltekit example to test this issue and support it.
> feat: adding support for esm modules entries

- src/rx-query-mingo.ts
- test/unit/rx-storage-query-correctness.test.ts
- A BUGFIX
The `$elemMatch` operator did not work for me after upgrading to 13.17.0. It seems like the array operators `$elemMatch`, `$all` and `$size` are not enabled in mingo anymore. But they are part of the RxQuery type definition:
https://github.com/pubkey/rxdb/blob/d828b8181e5c24c08d32429923508fa8d2e1a5ac/src/types/rx-query.d.ts#L20-L22
This PR enables them and adds a corresponding test.
> Add missing mingo array operators

- src/plugins/replication-p2p/connection-handler-simple-peer.ts
Importing `io` was not correct, and it caused the issue for my builds. 
The correct way to import `io` would be:
```
const { io } = require("socket.io-client");
```
and not
```
const io = require("socket.io-client");
```
According to the doc:
https://socket.io/docs/v4/client-initialization/
And this worked just fine at my side.
> Correct way to import socket.io-client in P2P Simple Peer Replication

- CHANGELOG.md
- docs-src/releases/14.0.0.md
- src/plugins/attachments/index.ts
- src/rx-document.ts
- src/types/rx-document.d.ts
- test/unit/reactive-document.test.ts
> CHANGE `RxDocument.$` now emits `RxDocument` instances instead of the plain document data.

- docs-src/rx-storage.md
The storage documentation page links to the wrong page.
> Fix Shared Worker link in rx-storage.md

- src/plugins/storage-lokijs/lokijs-helper.ts
- src/rx-query-helper.ts
- test/unit/rx-storage-query-correctness.test.ts
- A BUGFIX
If I use `null` in the selector RxDB crashes in this line:
https://github.com/pubkey/rxdb/blob/b24d101c2a7e4e28da207d6ea0c8d8fb4f317e5e/src/rx-query-helper.ts#L172
> Test and fix for crash with null in selector

- docs-src/replication-graphql.md
- src/plugins/replication-graphql/index.ts
- src/types/plugins/replication-graphql.d.ts
- src/types/plugins/replication.d.ts
- test/unit/replication-graphql.test.ts
- New feature that lets you define a responseModifier for GraphQL push replication to be able to covert any response to the format required by RxDB to detect conflicting documents
- New feature that lets you define a dataPath for the conflicting documents in a GraphQL push replication
- It's not possible to use RxDB with an advanced GraphQL setup where the server returns more than an array of conflicting documents on push replication
> Feature: Ability to use a responseModifier for GraphQL push replication

- src/plugins/replication-websocket/websocket-server.ts
- Ability to pass all websocket options to constructor. E.g. the custom http server.
Example usage:
```
import http from 'http'
const port = 3030
const server = http.createServer()
const serverState = startWebsocketServer({
database: db,
server: server,
})
server.listen(port, () => {
console.info(`Data stream server started on port ${port}`)
})
```
> feat(websocket-replication): pass all websocket options to constructor

- docs-src/replication-firestore.md
- src/plugins/replication-firestore/firestore-types.ts
- src/plugins/replication-firestore/index.ts
- src/plugins/utils/utils-array.ts
- test/replication-firestore.test.ts
1. We only want to sync a subset of our Firestore database with each client.
2. We only want to sync a subset of client's database with Firestore.
As an example for case 1, we have a user system and want to add ownership concept to documents. In that case we would need to apply a filter/query when fetching data from Firestore.
For case 2, we want our users to be able to choose which documents are synced with the cloud. So we need to filter the local documents and only replicate a subset of them to Firestore.
Here's my proposal for these problems:
```ts
const replicationState = replicateFirestore(
{
collection: myRxCollection,
firestore: {
projectId,
database: firestoreDatabase,
collection: firestoreCollection
},
pull: {
filter: [
where('ownerId', '==', userId)
]
},
push: { …
```
> feature(replication-firestore): add filtered replication

- src/types/rx-schema.d.ts
Otherwise any schema with a type like:
```
myfield: {
type: ["string", "null"],
},
```
will produce an error.
> fix: typescript schema to allow nullable fields

- src/rx-document.ts
- test/unit/hooks.test.ts
- A BUGFIX
``` js
// series
myCollection.preSave(function(plainData, rxDocument){
// rxDocument is always undefined in the latest version
console.log(rxDocument)
// modify anyField before saving
plainData.anyField = 'anyValue';
}, false);
```
https://rxdb.info/middleware.html
> fix: lost RxDocument in preSave from v14.0.0

- src/types/rx-schema.d.ts
- test/helper/schemas.ts
- test/typings.test.ts
IMPROVED typings
From combining the "typescript" and "composite primary key" sections, I got this error:
```
Types of property 'fields' are incompatible.
The type 'readonly ["app_id", "budget_id"]' is 'readonly' and cannot be assigned to the mutable type 'string[]'.
```
This error happens because adding the const modifier makes arrays be readonly, which have a more restrictive typechecking than readonly props.
I was looking to push a pull request, but I wasn't sure if this was a proper solution (it did fix the issue for me and I imagine it is backwards compat, although I'm not a typescript expert)
```
export type CompositePrimaryKey<RxDocType> = {
...
fields: readonly (StringKeys<RxDocType> | string)[] | (StringKeys<RxDocType> | string);
...
};
I also added `readonly` modifier to other …
```
> Add better support for `as const` schemas

- src/plugins/dev-mode/check-schema.ts
- test/unit/rx-schema.test.ts
- A BUGFIX
The dev mode plugin throws `"fieldnames do not match the regex"` for `fieldName:"0"` if the schema contains `anyOf` or an `items` array.
My patch seems to break the (negative) test for this schema. I'm not sure how this test was supposed to work. It seems like it only worked before because `checkSchema` had bugs with arrays.
https://github.com/pubkey/rxdb/blob/397ecf2a30fb8b58c705bd963d16aac6db0a1aff/test/helper/schemas.ts#L625-L650
> Fix checkSchema for anyOf and items array

- docs-src/replication-graphql.md
Some ternaries from the `pullHuman` resolver in the GraphQL replication documentation are incorrect.
Colons are where question marks should be.
> Fix graphql replication docu

- docs-src/electron.md
A note that `nodeIntegration` must be enabled would be neat, since it is disabled by default.
> Add a `nodeIntegration` notice

- src/plugins/utils/utils-promise.ts
FIX for 
https://github.com/pubkey/rxdb/issues/4804
> FIX #4804 requestIdlePromise broken in react-native

- docs-src/replication-couchdb.md
– typo fix in the `replication-couchdb.md` example
> Fix typo in replication-couchdb.md

- src/plugins/validate-z-schema/index.ts
- IMPROVED LOGGING
https://github.com/pubkey/rxdb/issues/4898
> Expose path in validate-z-schema error logs

- docs-src/rx-schema.md
> Fix typo in RxSchema documentation

- docs-src/crdt.md
Typo + removed `getCRDTConflictHandler` import because it's not used in the example
> Fix typo in CRDT plugin docs

- docs-src/SUMMARY.md
- docs-src/rx-collection.md
- test/unit/rx-collection.test.ts
`rxCollection.findByIds$` was removed in 14.0.0 ([changelog entry](https://github.com/pubkey/rxdb/blob/master/CHANGELOG.md#1400-8-february-2023-breaking-read-the-announcement)) but it's still mentioned in the docs, which is confusing.
NOTE: I also changed mentions of `findByIds$` to `findByIds.$` in test names (they actually use `findByIds.$` now)
> Docs: remove findByIds$

- src/plugins/dev-mode/check-schema.ts
- test/unit/bug-report.test.ts
- test/unit/rx-schema.test.ts
This is for #4926. It shows that if you use `patternProperties` to define the value of unknown keys, that it'll error due to schema key validation.
> Add test to show that you can't use `patternProperties` in schema

- docs-src/replication-websocket.md
I tried to use the WebSocket replication server with the code from the documentation. In my tests, the call to `replicateWithWebsocketServer` never completed. Adding a leading `/` to the path on the server seems to solve the issue.
> Fix path in docs for websocket server

- src/plugins/replication-firestore/index.ts
- src/plugins/replication-graphql/index.ts
- src/plugins/replication-nats/index.ts
- src/plugins/replication-webrtc/index.ts
- src/plugins/replication-websocket/websocket-client.ts
- src/plugins/replication/index.ts
- src/types/plugins/replication-graphql.d.ts
- src/types/plugins/replication.d.ts
- If there is no checkpoint yet, the pull handler's checkpoint is always `undefined`. According to the type definitions, the checkpoint is always a `CheckpointType`. I've updated the parameter types to be `CheckpointType | undefined`.
- It seems like the pull handler can also return no checkpoint if it did not pull anything and the replication just started. In the replication. In the replication plugin [code](https://github.com/pubkey/rxdb/blob/8b7e6c9197830bb1bcea5e9b2a412e9c5e6db401/src/plugins/replication/index.ts#L201-L204) it seems like the returned checkpoint should be `null` in this case. I've added `null` the the pull handler's return type, but I'm not sure if this is correct.
> Fix replication primitive pull checkpoint type

- src/plugins/utils/utils-error.ts
- a bug fix
issue with string replaceAll on react-native with expo (targets: "ESNext") not supported.
replace with a regex produces the same result.
https://stackoverflow.com/questions/13340131/string-prototype-replaceall-not-working
> replaceAll is not a function

- src/plugins/replication-graphql/helper.ts
- src/plugins/replication-graphql/index.ts
- src/types/plugins/replication-graphql.d.ts
- test/helper/graphql-server.ts
- test/unit/replication-graphql.test.ts
- A non-breaking new feature to the graphql-replication plugin to make it possible to support a custom fetch that fits the `typeof fetch`
- it always default to `window.fetch` otherwise it will be the responsibility of the lib user to make sure its custom fetch fits the fetch API even for the `then()` and the `catch()`
We imported the graphql-replication plugin and customized it to make the helper `graphQLRequest` support `axios` which is a must-to-have lib for our project, since we use it everywhere to auto manages the bearer refresh token (renewal) and makes sure all requests get the updated access token before making a new request with the `axios.interceptors.request.use` and we added custom logic to the `axios.interceptors.response.use` to handle graphql …
> Custom fetch to support axios for the graphQL replication

- docs-src/docs/releases/15.0.0.md
improved docs
Currently it's not clear how to convert RegExp into string while keeping the flags.
> docs: add info about $options to v15 release note

- CHANGELOG.md
- src/plugins/replication/index.ts
- src/replication-protocol/downstream.ts
- src/replication-protocol/upstream.ts
- test/unit/replication.test.ts
Replication observation mode ignored when push handler is waiting for response from backend
https://github.com/pubkey/rxdb/issues/5571
> test and fix #5571

- CHANGELOG.md
- orga/performance-trackings.md
- package.json
- src/plugins/key-compression/index.ts
- test/unit/bug-report.test.ts
- test/unit/key-compression.test.ts
[#5603](https://github.com/pubkey/rxdb/issues/5605)
> Bugfix/issue #5605 corrupt keys containing square bracket

- test/unit/replication-protocol.test.ts
- IMPROVED TESTSs
The reason for the stability test "many writes while replication" sporadically failing was actually a race condition in the test itself.
Sometimes the fork instance was written to first, which then lead to a write conflict. This could theoretically happen with any storage adapter, but those less performant (which loki and denokv seem to be) were more prone to hit that case.
By using `promiseSeries()`, it's now made sure that the master instance is written to first.
> fix race condition in test case leading to sporadic fails

- src/plugins/replication-webrtc/connection-handler-simple-peer.ts
Users may need to pass an RTCPeerConnection configuration object to simple-peer through the plugin. This simply adds an optional parameter to getConnectionHandlerSimplePeer.
This is mostly likely to be used to pass a custom ICE server list for STUN and TURN servers.
Issue #5835
> replication-webrtc: allow passing config to simple-peer

- package.json
An update to `firebase` to a version that pulls in a patched version of `undici`
The current version of `firebase` pulls in a vulnerable version of `undici`:
```
❯ osv-detector .
Loaded the following OSV databases:
npm (14444 vulnerabilities, including withdrawn - last updated Fri, 26 Apr 2024 18:50:43 GMT)
yarn.lock: found 1482 packages
Using db npm (14444 vulnerabilities, including withdrawn - last updated Fri, 26 Apr 2024 18:50:43 GMT)
undici@5.28.3 is affected by the following vulnerabilities:
GHSA-9qxr-qj54-h672: Undici's fetch with integrity option is too lax when algorithm is specified but hash value is in incorrect (https://github.com/advisories/GHSA-9qxr-qj54-h672)
GHSA-m4v8-wqvr-p9f7: Undici's Proxy-Authorization header not cleared on cross-origin redirect for dispatch, request, …
```
> fix: update `firebase` for security

- src/plugins/replication-graphql/query-builder-from-rx-schema.ts
- src/plugins/test-utils/schema-objects.ts
- src/plugins/test-utils/schemas.ts
- src/plugins/utils/utils-string.ts
- test/unit/replication-graphql.test.ts
This PR contains A NEW FEATURE
You can see the issue this PR intends to fix [here](https://github.com/pubkey/rxdb/issues/5969).
> feat: update GraphQL query builder functions to generate output fields for nested queries

- CHANGELOG.md
- docs-src/docs/rx-collection.md
- src/plugins/dev-mode/error-messages.ts
- src/rx-collection-helper.ts
- src/rx-collection.ts
- test/unit/rx-collection.test.ts
https://github.com/pubkey/rxdb/issues/5721
> FIX #5721 RxDB does not respond to collection.remove() changes

- src/plugins/utils/utils-error.ts
- src/types/rx-error.d.ts
- test/unit/util.test.ts
A BUGFIX
missing `extensions` field to the error object (v14 regression).
**Related discussion:** https://github.com/pubkey/rxdb/issues/5952
> fix: Add missing extensions error field to errorToPlainJson

- docs-src/docs/replication-firestore.md
> Adds missing replicationIdentifier to firestore docs

- src/plugins/replication-firestore/index.ts
- test/replication-firestore.test.ts
- A BUGFIX
I noticed some documents where missing when replicating from firestore. I traced down the issue to a bug in the `sameTimeQuery` in the firestore plugin where we're querying for a document field instead of querying for a document id.
I'm not sure how to test a change to this library on my project, could you advise on how to do so? I don't think I can use `npm link` because of the build steps required.
> Fixes firestore replication of multiple document with the same serverTimestamp

- docs-src/docs/articles/localstorage-indexeddb-cookies-opfs-sqlite-wasm.md
- Wrong unit `seconds` instead of `milliseconds` for the benchmark with OPFS
Off-topic, I was curious about the sentence after.
> We can see the sending the data to a webworker first is a bit slower which comes from the overhead of serializing and deserializing the data on both sides.
I wonder if transferring the object directly to the web worker would be faster.
- [MDN: Web Workers API: Transferring objects between threads](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Transferable_objects#transferring_objects_between_threads)
> Fix typo: seconds -> milliseconds

- src/plugins/dev-mode/dev-mode-tracking.ts
This patch removes 5 extra pixels in dev-mode
> fix: position of dev-mode iframe

- src/rx-query-helper.ts
- test/unit/rx-collection.test.ts
* Unit tests that shows the bug
* Fix for the bug
When you chain "findByIds" with "patch" or "modify" it throws an error like "there is not method named modify on doc". The issue is caused by "findByIds" returning a result in the form of a map witch is not handled in "runQueryUpdateFunction".
> fix(rx-query) findByIds not working with modify and patch

- src/plugins/replication-graphql/helper.ts
- src/plugins/replication-graphql/index.ts
- src/types/plugins/replication-graphql.d.ts
- test/unit/replication-graphql.test.ts
- A BUGFIX
- BREAKING
If we define a custom `dataPath` for the `graphQL` replication, we end up setting a different datapath for the pull and push rep. Pull rep does not handle the `data.` prefix while push already handles it with `result.data` 
I changed this to make both (pull and push) use the same function helper to extract the proper datapath if defined or not by the user.
Based on the unit tests, I found some that were testing only the pull replication and needed `data` as a prefix so I made the helper function the same as the current `pull.dataPath`, so it will request the user to add `data.` as a prefix, if you prefer the other way around, let me know. However, it makes sense if for any reason the default selector `['data', …
> fix(datapath) must be equivalent for pull and push

- src/rx-collection.ts
- test/unit/rx-collection.test.ts
Fixes #6599.
I also believe `fillObjectDataBeforeInsert` needs to be run before collecting primary keys, in case the primary key is set there.
> FIX bulkInsert with primary keys set in preInsert hook broken in v15.38.3 #6599

- docs-src/docs/replication-graphql.md
- examples/react-native/package.json
- src/plugins/replication-graphql/graphql-websocket.ts
- src/plugins/replication-graphql/index.ts
- src/types/plugins/replication-graphql.d.ts
- test/unit/replication-graphql.test.ts
This PR contains:
In our project we need more flexibility with replication subscription, particularly we want it to try reconnecting until the connection is established, even if server is not responding.
> added possibility to pass graphql-ws options into the replication options

- src/plugins/storage-mongodb/rx-storage-instance-mongodb.ts
The PR incorporates MongoDB's [wrapping client library](https://github.com/mongodb/specifications/blob/master/source/mongodb-handshake/handshake.rst#supporting-wrapping-libraries) specification for the connection handshake to allow library details to be included in the metadata written to `mongos` or `mongod` logs.
For example, this change would allow server-side logs such as the following:
> {"t":{"$date":"2024-01-27T23:10:40.108Z"},"s":"I","c":"NETWORK","id":51800,"ctx":"conn16235","msg":"client metadata","attr":{"remote":"127.0.0.1:1094","client":"conn16235","doc":{"driver":{`"name":"nodejs|RxDB"`,`"version":"6.12.0|16.0.0"`},"platform":"Node.js v18.18.2, LE","os":{"name":"linux","architecture":"x64","version":"5.15.133+","type":"Linux"}}}}
For anyone hosting clusters with connections …
> Include RxDB version details in MongoDB handshake

- docs-src/docs/replication-graphql.md
- src/plugins/replication-graphql/graphql-websocket.ts
- src/types/plugins/replication-graphql.d.ts
- test/unit/replication-graphql.test.ts
A new feature: ability to provide a connectionParams function as part of wsOptions 
When opening a websocket for a graphql subscription, we need to provide authorization headers to authenticate. Currently, this works fine on the initial connection, but if the original token provided expires and graphql-ws needs to reconnect, there is currently no way to update the headers. Calling .setHeaders on the replicationState does not change the headers rxdb provides to graphql-ws when reconnecting.
To fix this issue, we need to be able to provide a connectionParams function which will ensure that a fresh access token can always be sent as part of the connection headers.
> Allow connectionParams to be provided as part of wsOptions for replication-graphql

- docs-src/docs/encryption.md
- docs-src/docs/migration-schema.md
- docs-src/docs/rx-storage-shared-worker.md
Improved documentation for encryption, schema migrations, and shared workers
The documentation was a little unclear on:
- where to run replication if you are using SharedWorker storage
- where to run encryption if you are using SharedWorker or Worker storage
- how to set the password for encryption if you are using SharedWorker or Worker storage
- where to run migrations if you are using SharedWorker or Worker storage
-
> Added documentation for encryption, schema migrations, shared workers

- src/plugins/replication-firestore/index.ts
- a bugfix for the Firestore replication ignoring the initialCheckpoint variable, causing a new replication to replicate all documents 
- Firestore replication useless if the collection you wanna replicate has many documents
- adding documentation for the initialCheckpoint variable to https://rxdb.info/replication-firestore.html
Example how to 'build' the initialCheckpoint variable, something you could put in the docs:
```
// 1. Query Firestore for the "boundary" document.
let initialCheckpoint: any = null;
try {
const q = query(
collection(this.firestore, 'collection'), // Your Firestore collection
where('serverTimestamp', '>=', twoMonthsAgo), // Filter: serverTimestamp>= 2 months ago
orderBy('serverTimestamp', 'asc'), // Order by createdAt ascending
limit(1) // Get only the first …
```
> Fix Firestore replication ignoring initialCheckpoint

- docs-src/docs/migration-schema.md
The example code in the doc use a deprecated signature for rxjs subscribe, this PR replace it with the new version.
I looked for other instances of the deprecated signature being used and couldn't find any
> migration-schema docs: use non-deprecated subscribe signature

- .github/workflows/main.yml
- docs-src/docs/rx-storage-foundationdb.md
- scripts/install-foundationdb.sh
- test/unit/config.ts
FIxing the premium task for upgrading node-foundationdb to v2.0.1.
Local testing suggests that the only thing that is necessary is installing foundationdb client and server v7.3.xx. You can then specify any apiVersion _except_ 730. 
Ive opened an issue at node-foundationdb about this https://github.com/josephg/node-foundationdb/issues/85
Hopefully the tests will pass with this PR
> Fix foundationdb premium task

- dist/types/plugins/dev-mode/error-messages.d.ts
- src/plugins/dev-mode/error-messages.ts
- src/rx-database.ts
- test/unit/rx-database.test.ts
- A BREAKING CHANGE (kind of?)
The problem is described and discussed here: https://github.com/pubkey/rxdb/issues/6988
This PR makes the `DB8` erro obsolete because a new instance with the same db-name and storage will only initialize when no other with the same combination exists:
```js
const db1Promise = createRxDatabase({ name, storage });
const db2Promise = createRxDatabase({ name, storage }); // this promise will only resolve once db1 is closed and db2 is fully initialized
```
In the issue above I've also mentioned to implement a `AbortSignal` parameter which is not contained in this PR yet as I want to first wait for feedback.
> feat: db8 error handling

- docs-src/docs/replication-firestore.md
Update the `replicateFirestore` documentation to emphasize that the options require `push` and `pull` to be present as empty objects (or with an optional `filter` member) to enable those types of replication.
> Mention required parameters for firestore replicateFirestore

- src/types/plugins/migration.d.ts
The `MigrationStrategy` uses a generic type. When using the `MigrationStrategies` this is set to `any`. This PR makes it able to set the type of `MigrationStrategy` even when using `MigrationStrategies`.
This will allow us to enforce a type as the param type for each migration, if we set it correctly once, it will be correct for all
> MigrationStrategies type not generic

- src/plugins/replication/index.ts
- A BUGFIX
When the `toggleOnDocumentVisible` flag was `true` our app started hanging on Safari iOS, further explanation can be found [here](https://github.com/pubkey/rxdb/issues/6810#issuecomment-2815932461) and [here](https://github.com/pubkey/rxdb/issues/6810#issuecomment-2816648422).
I firmly believe that `replicationState.start()` also has some side-effects which cause this problem to even happen.
This PR only fixes the `visibilitychange` event handler, so that it is not only starting the replication, since `document.visibilityState` is a string and not a boolean.
> fix toggleOnDocumentVisible isVisible not always truthy

- src/plugins/state/rx-state.ts
- test/unit/rx-state.test.ts
1. a test case to reproduce
2. fix issue
state get changes from other states will get follow errors. it cannot set correct state because devmode
```bash
AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:
+ actual - expected
{
+   ted: 'foo'
-   ted: 'foo2'
}
+ expected - actual
{
-  "ted": "foo"
+  "ted": "foo2"
}
```
[the ci result](https://github.com/kryon-7/rxdb/actions/runs/14568603267)
> state get changes from other state will get error

- src/plugins/pipeline/rx-pipeline.ts
- test/unit/rx-pipeline.test.ts
a bugfix and test for it
When all the incoming documents have been handled by pipeline if localDocument gets inserted pipeline never unlocks query to execute over destination collection.
> fixed query hanging after local document inserted
