README.md

This project looks really exciting! This PR is just for a formatting adjustment (consistent chained function indentation) from while i was reading the readme.

format chained functions in readme with two space indentation

---

README.md

There was a _very_ small typo that I see above the fold, I feel everything should look great on the readme.md if it's going to be the first thing people see! ☺️

FIX minor readme typo

---

src/KeyCompressor.js
test/node/KeyCompression.test.js

KeyCompressor did not work on top-level array.

FIX bug #50

---

docs/LeaderElection.md

Hi,
I found some minor spelling errors.
Looks like a great project- keep up the good work!

Typo in docs

---

README.md
docs/RxCollection.md
src/RxCollection.js
src/index.d.ts

Hi @pubkey, please have a look, i think this PR useful for setup the PouchDB settings for example: set the persistent/temporary database type on IndexedDB adapter

Fix ability to set PouchDB settings

---

docs/DataMigration.md
docs/Install.md
docs/LeaderElection.md

Docs updates

---

docs/Contribute.md
docs/DataMigration.md

As an assignment for a technical writing course, we were told to edit documentation on projects on GitHub

DataMigration.md edits

---

docs/RxDocument.md

instead of unique to MySql which the statement is not

docs RxDocument reword to make a little more generic

---

src/index.d.ts

fix typings of CollectionCreator

---

package.json

Move babel preset to devDeps

---

package.json
src/RxCollection.js
src/RxDocument.js
src/RxQuery.js
test/unit/RxCollection.test.js
test/unit/RxDocument.test.js

Revert "Revert "added update functionality""

---

src/index.d.ts

I think it is useful to export the CollectionCreator interface as well in typescript.

Typescript improvements for CollectionCreator

---

.editorconfig
.gitignore
src/index.d.ts

- Improve typings for queries (closes #326)
- Improve typings for collections (instead of #321)
- Add `.editorconfig` to make sure IDEs follow the repo's format
- Add `.idea` in `.gitignore` to remove Jetbrains IDE temporary files
**Todo**:

Improve typings

---

docs-src/query-change-detection.md

Grammar fix: Added a possessive apostrophe.

---

docs-src/query-change-detection.md

Some minor grammatical updates for clarity.

---

README.md
docs-src/contribute.md
docs-src/custom-build.md
docs-src/data-migration.md
docs-src/leader-election.md
docs-src/middleware.md
docs-src/plugins.md
docs-src/population.md
docs-src/replication.md
docs-src/rx-attachment.md
docs-src/rx-collection.md
docs-src/rx-local-document.md
docs-src/rx-schema.md
orga/BACKLOG.md
orga/release-checklist.md

docs: fix typos

---

test/unit/rx-query.test.js

Improved tests
Issue https://github.com/pubkey/rxdb/issues/157 still not resolved. Added a test that replicates that.
Using newest version (7.3.0)
Modified https://github.com/pubkey/rxdb/pull/434 with `disableKeyCompression`

Add more tests for issue #157.

---

docs-src/population.md

underscore suffix

---

docs-src/custom-build.md

This PR contains a small fix to the documentation.

Fix variable name in custom build docs

---

src/rx-schema.js
test/unit/rx-schema.test.js

indexes are not implicitly marked as 'required' anymore

---

README.md

- Add links and frameworks 
- Add License

Add links frameworks and license

---

docs-src/orm.md

FIX missing return in docs

---

docs-src/middleware.md

Minor typo fix in the documentation

---

docs-src/middleware.md

docs: add this binding for middleware hooks

---

examples/react/package.json
examples/react/src/App.jsx
examples/react/src/Database.jsx
examples/react/src/hero-insert/hero-insert.jsx
examples/react/src/hero-list/hero-list.jsx

Basically make it easier to read.
Improvements to the React example app
React example just needed some clean up

[examples React]: Clean up

---

src/rx-database.js

Should we not also `await` or chain L699 somehow?

Returns promise from RxDB.removeDatabase

---

docs-src/adapters.md

- Improved docs: it fixes a small typo in the Adapters docs
N.A.

Fix small typo in Adapter docs

---

src/rx-document.js
test/helper/humans-collection.js
test/unit/rx-document.test.js
typings/rx-document.d.ts

Fixes #1325

---

CHANGELOG.md
src/plugins/server.js
test/unit/server.test.js

BUGFIX for #1450
Cors headers not properly set #1450

BUGFIX for #1450

---

.npmignore

fix for #1509 
Ignored errors after npm install see issue.
There is no test for this fix, and an `npm publish` is required before the issue should be closed.

fix: remove scripts dir from npmignore; will fix #1509 after npm publish

---

docs-src/questions-answers.md

fixed typo

---

docs-src/tutorials/server.md

fix: small typo

---

docs-src/contribute.md

- Improved Docs
A Broken link  in contribute.md

Fix link to bug-report.test.ts in contribute.md

---

src/plugins/error-messages.ts

Does as the title states, also adds an extra space.

Fix grammar

---

docs-src/install.md

- typo fix in the documentation page
Grammar error

Fix typo in documentation

---

docs-src/tutorials/server.md

Typo line 11

---

docs-src/tutorials/typescript.md

Removed duplicate 'createRxDatabase' in the declaration.
- IMPROVED DOCS in TypeScript tutorial
Duplicate in the declaration.

Remove duplicate

---

docs-src/tutorials/typescript.md

postInsert / preInsert mis-match in tutorial docs

---

examples/graphql/server/index.js

Fix this TypeError: graphqlHTTP is not a function

---

examples/react/src/Database.jsx

- A BUGFIX
Add missing RxDBLeaderElectionPlugin import  to react-example

FIX add LeaderElectionPlugin and RxDBReplicationPlugin to react-example

---

examples/vanilla/main.js

- A BUGFIX
Vanilla.js example not working

Vanilla.js example fix

---

docs-src/rx-document.md

There is a typo in the documentation.

Correct typo in document update example

---

docs-src/replication-graphql.md
src/plugins/replication-graphql/index.ts
test/unit/replication-graphql.test.ts

Feature: Allow to skip docs in push/pull modifiers

---

docs-src/replication.md

Updated replication.md with sync limitations

---

CHANGELOG.md
docs-src/rx-attachment.md
docs-src/rx-collection.md

Fix minor typos in `rx-collection.md`, `rx-attachment.md`, and `CHANGELOG.md`. 
If you have any "wish list" changes you would like made to RxDB's documentation or README, please let me know. An example of this would be to update all uses of `db.collection(...)` to the new `db.addCollections(..)`.

Fix typos in docs and changelog

---

docs-src/rx-collection.md

.addCollections() was misspelled as .addCollection()

fixing type in function name

---

src/rx-collection.ts
test/unit/reactive-collection.test.ts

fix: rxDocument of changeEvent which produced by collection.bulkInsert is not a RxDocument instance

---

src/rx-collection.ts
test/unit/hooks.test.ts

FIX postInsert hook not working when use bulkInsert to insert doc

---

docs-src/install.md

Improved Docs
Information about bundler configuration and examples.
Issue #2998

Docs - Info about project configuration

---

examples/electron/test/spec.js

typo test fix;

---

docs-src/rx-collection.md

The intention of this PR is to fix #3216 , and as such it should not be merged until all the questions of the issue are resolved, and it is agreed that the added documentation covers the clarified information.

Update documentation on importing

---

docs-src/rx-local-document.md

small typo fix

---

src/rx-collection.ts

the type of RxCollection.database is any

Fix the type of RxCollection.database is any

---

README.md

FIX docs for install package

---

docs-src/replication-graphql.md
docs/replication-graphql.html
src/plugins/replication-graphql/index.ts
src/rx-query.ts
test/helper/graphql-server.ts
test/unit/cross-instance.test.ts
test/unit/reactive-query.test.ts
test/unit/replication-graphql.test.ts

- SOMETHING ELSE
Fixing misspelled `recieved` -> `received`
Because this touches code I think its a breaking change.

fix spelling of recieved => received

---

docs-src/replication-couchdb.md

- a small typo fix for the docs
- a typo in the docs

Fix typo in replication-couchdb.md

---

docs-src/rx-database.md

I copied and pasted the example, but was returned this error: "getRxStoragePouch is not defined".

fix: add missing property from rxdb

---

docs-src/offline-first.md

- A TYPO FIX
The docs read `So if we did no care about`, which I fixed to `So if we did not care about`

Update offline-first.md to fix typo

---

examples/vanilla/main.js

Vanilla example doesn't work
I think this is correct... at least the console doesn't throw errors and the demo seems to work.

Fixed vanilla example

---

src/plugins/dev-mode/error-messages.ts

A Typo
Error message for DB9 is missing a closing paren

Add missing paren

---

docs-src/alternatives.md

- improved docs
Various typos and grammar mistakes in the docs

Various changes for grammar and correction of typos

---

src/plugins/dev-mode/error-messages.ts

- A minor fix to an error message
Grammar
N/A (I don't see a point for changelog for such a small thing)

Update error message

---

src/plugins/replication/index.ts
src/plugins/replication/replication-checkpoint.ts
test/unit/replication.test.ts

Contains the test of https://github.com/pubkey/rxdb/pull/3729
and a fix.

11bit repro/infinite push loop

---

test/unit/replication.test.ts

Test for infinite push loop in replication primitives

---

src/plugins/dexie/rx-storage-instance-dexie.ts
src/plugins/encryption.ts
src/plugins/lokijs/rx-storage-instance-loki.ts
src/plugins/pouchdb/custom-events-plugin.ts
src/plugins/pouchdb/rx-storage-instance-pouch.ts
src/rx-database-internal-store.ts
src/rx-database.ts
src/rx-storage-helper.ts
src/types/rx-storage.d.ts
test/unit/rx-database.test.ts
test/unit/rx-storage-implementations.test.ts

ADD conflict errors must contain document state from database

---

src/plugins/dexie/dexie-helper.ts
test/unit.test.ts
test/unit/dexie-helper.test.ts

- A BUGFIX
fix https://github.com/pubkey/rxdb/pull/3778

fix pull/3778

---

config/.mocharc.js
docs-src/adapters.md
docs-src/plugins.md
orga/releases/12.0.0.md
src/overwritable.ts

There were grammatical and lint errors.

docs: Cleaned up English grammar in a few more places

---

.gitignore
CHANGELOG.md
src/plugins/attachments.ts
src/plugins/local-documents/local-documents.ts
src/plugins/local-documents/rx-local-document.ts
src/plugins/migration/data-migrator.ts
src/plugins/replication/index.ts
src/rx-collection.ts
src/rx-database.ts
src/rx-document.ts
src/rx-query.ts
src/rx-storage-helper.ts
src/types/rx-document.d.ts
test/unit.test.ts
test/unit/data-migration.test.ts
test/unit/rx-collection.test.ts
test/unit/rx-database.test.ts
test/unit/rx-document.test.ts
test/unit/rx-query.test.ts
test/unit/rx-storage-implementations.test.ts

WIP REFACTOR revision handling

---

docs-src/dev-mode.md

Update dev-mode add note about schema validation

---

docs-src/transactions-conflicts-revisions.md

Fix typo in transactions-conflicts-revisions.md

---

CHANGELOG.md
src/index.ts
src/plugins/dev-mode/index.ts
src/plugins/dexie/rx-storage-instance-dexie.ts
src/plugins/lokijs/rx-storage-instance-loki.ts
src/plugins/memory/memory-types.ts
src/plugins/memory/rx-storage-instance-memory.ts
src/plugins/pouchdb/rx-storage-instance-pouch.ts
src/plugins/worker/in-worker.ts
src/plugins/worker/non-worker.ts
src/rx-collection.ts
src/rx-database.ts
src/rx-storage-helper.ts
src/rx-storage-replication.ts
src/types/conflict-handling.d.ts
src/types/index.d.ts
src/types/rx-collection.d.ts
src/types/rx-document.d.ts
src/types/rx-query.d.ts
src/types/rx-storage-replication.d.ts
src/types/rx-storage.interface.d.ts
test/unit.test.ts
test/unit/cleanup.test.ts
test/unit/conflict-handling.test.ts
test/unit/rx-storage-replication.test.ts

WIP REFACTOR conflict handling

---

CHANGELOG.md
src/plugins/dexie/rx-storage-instance-dexie.ts
src/plugins/pouchdb/custom-events-plugin.ts
src/rx-storage-helper.ts
test/unit/rx-collection.test.ts
test/unit/rx-document.test.ts
test/unit/rx-storage-implementations.test.ts

START working on a solution for #3839

---

docs-src/tutorials/typescript.md

`heroSchema` is inconsistent without this.

add `age` to heroSchemaLiteral

---

docs-src/rx-query.md

no mention of `unsubscribe` in docs.

adding example of unsubscribe to docs

---

package.json
src/plugins/local-documents/local-documents.ts
src/rx-collection.ts
src/rx-database-internal-store.ts
src/rx-database.ts
src/types/rx-database.d.ts
src/types/rx-schema.d.ts
src/types/rx-storage.d.ts

Upgrade TypeScript to 4.8.x

---

test/unit.test.ts
test/unit/query-correctness.test.ts

ADD test for query correctness

---

CHANGELOG.md
config/karma.conf.js
src/util.ts
test/unit/attachments.test.ts

ADD test for attachment not working in the browser

---

test/helper/spawn-server.ts
test/unit/replication-couchdb.test.ts
test/unit/server-couchdb.test.ts

FIX no hardcoded port numbers

---

config/karma.conf.js

Ignored SafariTechPreview in test

---

.github/ISSUE_TEMPLATE.md

TYPOFIX: Format the "questions" prompt to look like the others section titles.

---

CHANGELOG.md
package.json
src/index.ts
src/plugins/dev-mode/check-query.ts
src/plugins/dev-mode/index.ts
src/plugins/lokijs/rx-storage-lokijs.ts
src/plugins/pouchdb/pouch-statics.ts
src/query-planner.ts
src/rx-query-helper.ts
src/types/modules/deep-freeze.d.ts
src/util.ts
test/helper/schema-objects.ts
test/unit/rx-storage-implementations.test.ts
test/unit/rx-storage-query-correctness.test.ts

WIP ADD more test for queries

---

CHANGELOG.md
docs-src/releases/13.0.0.md
package.json
src/index.ts
src/plugins/replication-graphql/helper.ts
src/plugins/replication-graphql/index.ts
src/types/modules/graphql-client.d.ts
src/types/plugins/replication-graphql.d.ts
test/helper/graphql-config.ts
test/helper/graphql-server.ts
test/unit/replication-graphql.test.ts

REMOVE `graphql-client` dependency

---

scripts/transpile.js
test/unit/config.ts
test/unit/data-migration.test.ts

WIP improve test runs

---

package.json

WIP UPDATE ws

---

examples/electron-remote/README.md
examples/electron/package.json
src/index.ts
src/plugins/electron/electron-helper.ts
src/plugins/electron/rx-storage-ipc-main.ts
src/plugins/electron/rx-storage-ipc-renderer.ts
src/rx-storage-message-channel.ts

REFACTOR message channel storage

---

CHANGELOG.md
examples/electron/main.js
src/plugins/electron/rx-storage-ipc-main.ts
src/plugins/electron/rx-storage-ipc-renderer.ts
src/rx-storage-message-channel.ts

CHORE refactor again

---

docs-src/replication.md

Found a small typo, thought it might help
Not an issue, but just saw a small typo.

Update replication.md - small typo

---

CHANGELOG.md
orga/before-next-major.md
src/plugins/backup/index.ts
src/rx-collection.ts
src/rx-document.ts
src/rx-query.ts
src/types/rx-query.d.ts
test/unit/rx-collection.test.ts

CHANGE `RxCollection.findByIds()` now returns a `RxQuery`

---

CHANGELOG.md
src/plugins/replication/index.ts
src/replication-protocol/checkpoint.ts
src/replication-protocol/downstream.ts
src/replication-protocol/meta-instance.ts
src/rx-schema-helper.ts
src/types/replication-protocol.d.ts
test/unit/replication-protocol.test.ts
test/unit/replication.test.ts

REFACTOR how the meta instances of a replication stores the data.
Also FIXES https://github.com/pubkey/rxdb/issues/4315

REFACTOR replication hash id

---

examples/flutter/pubspec.yaml
src/plugins/flutter/dart/pubspec.yaml

Mirror https://github.com/pubkey/rxdb/pull/4301

Renovate/shared preferences 2.x

---

examples/svelte/package.json

Mirror https://github.com/pubkey/rxdb/pull/4266

Renovate/sirv cli 2.x

---

docs-src/replication-couchdb.md
package.json
src/plugins/dev-mode/error-messages.ts
src/plugins/replication-couchdb/couchdb-helper.ts
src/plugins/replication-couchdb/index.ts
test/helper/spawn-server.ts
test/unit.test.ts
test/unit/replication-couchdb.test.ts

Related: https://github.com/pubkey/rxdb/pull/4319

UPDATE couchdb to version 3

---

docs-src/query-optimizer.md

Fix typo in query optimizer docs

---

docs-src/rx-storage-sqlite.md

Fix typo in SQLite storage documentation

---

src/rx-query-mingo.ts
test/unit/rx-storage-query-correctness.test.ts

- A BUGFIX
Using `$type` in a query throws an exception

Fix mingo $type import and add test

---

docs-src/react-native-database.md

i did remove word  "that" has being added by mistake
i did removed a word that have being added by mistake

FIx react-native-database.md

---

docs-src/premium.html

blocked 'e' from team size input

---

CHANGELOG.md
src/rx-document.ts
src/types/rx-document.d.ts
test/unit/reactive-document.test.ts

Fixes https://github.com/pubkey/rxdb/pull/4548

FIX RxDocument getter should return the same object on property paths #4548

---

docs-src/rx-database.md

[Docs] Update database.remove description

---

docs-src/third-party-plugins.md

Context: https://github.com/orgs/supabase/discussions/357#discussioncomment-3579887

Add rxdb-supabase to third-party-plugins.md

---

docs-src/query-optimizer.md

Fix typo in query-optimizer.md

---

docs-src/rx-storage-sqlite.md

adding info about `getDatabaseConnection`
fixes #4700

add note about `getDatabaseConnection`

---

test/unit/rx-storage-implementations.test.ts

ADD test for umlauts

---

src/plugins/replication-couchdb/couchdb-helper.ts

remoteRevById.set(row.id, row.doc._rev);
doc._rev should not be undefined

Fix prevent delete _rev from row.doc

---

docs-src/rx-storage-localstorage-meta-optimizer.md

Fix typo in localstorage-meta-optimizer-docs

---

examples/electron/README.md

Fix Electron example docs

---

src/plugins/replication-graphql/index.ts
test/unit/replication-graphql.test.ts

FIX #4781 GraphQL Replication Cancel With Database Destroy Bug Report

---

CHANGELOG.md
src/custom-index.ts
src/plugins/storage-foundationdb/foundationdb-query.ts
src/plugins/storage-memory/rx-storage-instance-memory.ts
test/unit/config.ts
test/unit/rx-collection.test.ts
test/unit/rx-query.test.ts
test/unit/rx-storage-implementations.test.ts
test/unit/rx-storage-query-correctness.test.ts

https://github.com/pubkey/rxdb/pull/4775

ADD test for #4775

---

CHANGELOG.md
src/plugins/storage-dexie/rx-storage-instance-dexie.ts
test/unit/rx-storage-query-correctness.test.ts

Slow count is broken #4755

---

docs-src/rx-query.md

Fix typo in RxQuery docs

---

docs-src/third-party-plugins.md

Rename `orion` plugin 

---

.github/workflows/main.yml
CHANGELOG.md
README.md
src/plugins/storage-dexie/dexie-query.ts
src/plugins/storage-foundationdb/foundationdb-query.ts
src/plugins/storage-memory/rx-storage-instance-memory.ts
test/unit/rx-storage-query-correctness.test.ts

https://github.com/pubkey/rxdb/pull/4751

$lt selector on primaryKey on RxStorageDexie

---

docs-src/rx-schema.md

docs(docs-src): Fix typo in rx-schema.md

---

orga/before-next-major.md
src/plugins/dev-mode/check-schema.ts
src/plugins/dev-mode/error-messages.ts
test/unit/rx-schema.test.ts

https://github.com/pubkey/rxdb/issues/4926#issuecomment-1712223984

Feature/15 disallow $ref  fields

---

docs-src/rx-collection.md
orga/before-next-major.md
src/rx-collection.ts
src/rx-storage-helper.ts
test/unit/rx-collection.test.ts

https://github.com/pubkey/rxdb/issues/4821#issuecomment-1660339676

REFACTOR bulkUpsert

---

docs-src/releases/15.0.0.md
orga/performance-trackings.md
src/custom-index.ts
src/plugins/utils/utils-object-dot-prop.ts
src/plugins/utils/utils-string.ts
src/rx-database-internal-store.ts
src/rx-document.ts
src/rx-schema.ts
test/helper/schema-objects.ts
test/performance.test.ts
test/unit/cross-instance.test.ts
test/unit/encryption.test.ts
test/unit/rx-document.test.ts

Using Proxy API instead of defining getters

IMPROVE property access performance

---

src/plugins/dev-mode/error-messages.ts
src/rx-storage-helper.ts
test/unit/rx-collection.test.ts

https://github.com/pubkey/rxdb/issues/5046

ADD helpfull error message for #5046

---

docs-src/rx-storage.md
examples/README.md
orga/before-next-major.md
orga/performance-trackings.md

This pull request fixing typos from folder `./docs-src`. I kindly request repository maintainers to review it and merge it. 
Capactior -> Capacitor
repositiory -> repository 
helpfull -> helpful 
Juli -> July 
strorage -> storage 
This PR corrects some of the spelling error.

docs-src: fixed typos

---

test/replication-firestore.test.ts

https://github.com/pubkey/rxdb/pull/4698

ADD test for #4698 firestore replication

---

docs-src/database.ts
docs-src/premium.html
docs-src/premium.ts
docs-src/styles/landingpage.css

update pricing calculator

---

test/unit/validate.test.ts

https://github.com/pubkey/rxdb/pull/5197

ADD test for #5197 - can't get data for object field defined with additionalProperties

---

docs-src/releases/15.0.0.md
docs-src/replication-graphql.md
docs-src/replication.md
src/plugins/replication/index.ts
src/types/plugins/replication.d.ts
test/unit/replication-graphql.test.ts
test/unit/replication.test.ts

https://github.com/pubkey/rxdb/issues/5256

FIX PushModifier applied to pre-change legacy document, resulting in old document sent to endpoint

---

src/query-planner.ts
test/unit/rx-storage-query-correctness.test.ts

https://github.com/pubkey/rxdb/issues/5273

ADD test for #5273

---

docs-src/docs/releases/15.0.0.md
src/plugins/utils/utils-blob.ts

https://github.com/pubkey/rxdb/issues/5311

FIX #5311 URL.createObjectURL is not a function

---

docs/premium.html

Fixed some wording on your premium page.

Wording Fixes On Premium Page

---

docs-src/docs/crdt.md
docs-src/docs/releases/15.0.0.md
docs-src/docs/rx-document.md
package.json
src/plugins/crdt/index.ts
src/plugins/update/index.ts
src/plugins/update/mingo-updater.ts
src/types/modules/modifiyjs.d.ts
src/types/plugins/update.d.ts

https://github.com/pubkey/rxdb/issues/5358

rEFACTOR use mingo for updates

---

docs-src/docs/releases/15.0.0.md
docs-src/docs/rx-storage-dexie.md
src/plugins/dev-mode/error-messages.ts
src/plugins/storage-dexie/dexie-helper.ts
src/plugins/storage-dexie/dexie-query.ts
src/plugins/storage-dexie/rx-storage-dexie.ts
src/plugins/storage-dexie/rx-storage-instance-dexie.ts
src/types/plugins/dexie.d.ts
test/unit/config.ts
test/unit/rx-schema.test.ts
test/unit/rx-storage-dexie.test.ts
test/unit/rx-storage-implementations.test.ts
test/unit/rx-storage-query-correctness.test.ts

Refactor the dexie.js storage:
- Make it support boolean indexes
- Add support for attachments
- ensure it is compatible with the planned rxstorage changes for the server plugin

REFACTOR dexie storage

---

.eslintrc.json
src/plugins/dev-mode/check-schema.ts
src/plugins/utils/utils-object.ts
src/query-planner.ts
src/rx-collection-helper.ts
src/rx-schema-helper.ts
src/rx-schema.ts
src/rx-storage-helper.ts
test/unit/replication-graphql.test.ts
test/unit/rx-storage-lokijs.test.ts

https://github.com/pubkey/rxdb/pull/5391

ADD lint no-prototype-builtins

---

src/plugins/electron/rx-storage-ipc-main.ts

A BUGFIX
[#5370](https://github.com/pubkey/rxdb/issues/5370)

fix(src:plugins:electron): Object has been destroyed

---

CHANGELOG.md
src/plugins/crdt/index.ts
test/unit/crdt.test.ts
test/unit/replication-graphql.test.ts

https://github.com/pubkey/rxdb/pull/5423

FIX #5423 CRDT with undefined fields

---

docs-src/docusaurus-lunr-search-main/src/utils.js
docs-src/docusaurus.config.ts

Filter function - added blog + releases

- particular fix for excluding routes - !!! Its a simple split.some.filter fix

---

docs-src/docs/crdt.md

Update crdt.md  Just fixed the word RxDB

---

CHANGELOG.md
src/plugins/key-compression/index.ts
test/unit/key-compression.test.ts

https://github.com/pubkey/rxdb/pull/5492

FIX #5492 .count() with key-compression plugin

---

docs-src/docs/replication-webrtc.md
examples/angular/README.md
src/plugins/dev-mode/error-messages.ts
src/plugins/replication-webrtc/connection-handler-simple-peer.ts

ADD check for #5554

---

src/plugins/dev-mode/index.ts

Addresses #5556 by adding an exported `disableWarnings()` function which does what it says on the tin.

Optionally supress dev mode Warning

---

CHANGELOG.md
src/replication-protocol/meta-instance.ts
test/replication-firestore.test.ts

https://github.com/pubkey/rxdb/issues/5572

FIX #5572 firestore replication not working with schema validation

---

CHANGELOG.md
src/plugins/storage-lokijs/rx-storage-instance-loki.ts
src/plugins/utils/utils-object.ts
test/unit/rx-storage-query-correctness.test.ts

https://github.com/pubkey/rxdb/issues/5320

$in query on arrays #5320

---

docs-src/docs/replication-webrtc.md
examples/angular/README.md

docs: fix polyfill for process.nextTick

---

CHANGELOG.md
src/plugins/storage-remote/rx-storage-remote.ts

reported via discord https://discord.com/channels/969553741705539624/1059149217718861935/1204192534931447948

BUG: encryption not working from inside worker

---

CHANGELOG.md
src/plugins/test-utils/schemas.ts
src/plugins/utils/utils-string.ts
test/unit/encryption.test.ts
test/unit/util.test.ts

Add tests for arraybuffer-string conversions with very big strings. Related https://github.com/pubkey/rxdb/issues/5624#issuecomment-1944087621

FIX arraybuffer<->string conversions

---

docs-src/docs/rx-storage-opfs.md

Someone is wrong on the Internet `;-)`.

Fix some incorrect OPFS statements

---

docs-src/src/pages/index.tsx

- changed the slick slider rules on mobile

- react-slick slider - mobile fix

---

examples/react-native/README.md

This is a simple PR which adds [Tunnelmole](https://tunnelmole.com/docs) as an open source tunneling option.

Add Tunnelmole (FOSS tunneling tool)

---

CHANGELOG.md
docs-src/docs/rx-state.md
docs-src/sidebars.js
package.json
src/hooks.ts
src/plugins/cleanup/cleanup-state.ts
src/plugins/cleanup/index.ts
src/plugins/query-builder/index.ts
src/plugins/state/helpers.ts
src/plugins/state/index.ts
src/plugins/state/rx-state.ts
src/plugins/state/types.ts
src/rx-database.ts
src/types/index.d.ts
src/types/plugins/lokijs.d.ts
src/types/plugins/state.d.ts
src/types/plugins/update.d.ts
src/types/rx-document.d.ts
src/types/rx-plugin.d.ts
src/types/rx-query.d.ts
src/types/util.d.ts
test/unit.test.ts
test/unit/rx-state.test.ts
test/unit/util.test.ts

state lib on top of RxDB so people can store stuff without having to create collections for everything

---

docs-src/docs/rx-storage.md

ADD storage configuration examples

---

src/plugins/dev-mode/error-messages.ts

A fix to one of the error messages to make it grammatically correct
The error message is not grammatically correct

fix: remove duplicate "see" in error message

---

docs-src/package.json
docs-src/src/css/custom.css
docs-src/src/pages/consulting.tsx

fix(conculting page): removed unnecessary browserOnly wrappers

---

CHANGELOG.md
src/plugins/state/rx-state.ts
test/unit/rx-state.test.ts

Fixes https://github.com/pubkey/rxdb/pull/6084

FIX rx-state multi instance observable broken #6084

---

CHANGELOG.md
src/plugins/storage-dexie/dexie-helper.ts
src/plugins/storage-dexie/dexie-query.ts
src/plugins/storage-dexie/rx-storage-instance-dexie.ts
test/unit/key-compression.test.ts

https://github.com/pubkey/rxdb/pull/6267

FIX key-compression broken on dexie with boolean indexes

---

src/rx-document.ts

This PR tries to improve performance on nested property access: https://github.com/pubkey/rxdb/pull/6405

IMPROVE performance of nested property access

---

CHANGELOG.md
src/plugins/state/helpers.ts
src/plugins/state/rx-state.ts
test/unit/rx-state.test.ts

https://github.com/pubkey/rxdb/pull/6462

FIX RxState.property$ should emit stable reference #6462

---

CHANGELOG.md
examples/angular/package.json
examples/graphql/package.json
examples/react/package.json
examples/svelte/package.json
examples/vite-vanilla-ts/package.json
examples/vue/package.json
test/unit/rx-storage-query-correctness.test.ts

Here we add some tests to make sure that `$nin` works correctly in all storages.

FIX `$nin` queries not working correctly with the SQLite RxStorage

---

CHANGELOG.md
src/plugins/state/rx-state.ts
test/unit/rx-state.test.ts

https://github.com/pubkey/rxdb/pull/6503

FIX bad RxState after cleanup #6503

---

docs-src/docs/quickstart.md

(docs) typo correction in quickstart

---

CHANGELOG.md
src/plugins/dev-mode/error-messages.ts
src/rx-collection.ts
test/unit/rx-collection.test.ts

https://github.com/pubkey/rxdb/pull/6589

FIX bulk inserting 2 docs with same primary key should throw #6589

---

src/replication-protocol/index.ts

This adds more info to the error thrown in #6690

ADD more info to error

---

.github/workflows/main.yml
CHANGELOG.md
package.json
src/plugins/dev-mode/check-query.ts
src/plugins/dev-mode/error-messages.ts
src/plugins/utils/utils-object.ts
src/query-cache.ts
src/rx-query-helper.ts
src/rx-query.ts
test/unit/reactive-query.test.ts
test/unit/rx-query.test.ts
test/unit/rx-storage-query-correctness.test.ts

https://github.com/pubkey/rxdb/issues/6792

ADD dev-mode check for `undefined` properties in queries #6792

---

CHANGELOG.md
src/query-planner.ts
src/rx-query-helper.ts
test/unit/query-planner.test.ts
test/unit/rx-collection.test.ts

https://github.com/pubkey/rxdb/pull/6925

FIX #6925 col.find() ignores the primaryKey index if another index was defined

---

dist/types/plugins/dev-mode/error-messages.d.ts
src/plugins/dev-mode/error-messages.ts
src/rx-database.ts
test/unit/rx-database.test.ts

Accidentiall merged.
Reverts pubkey/rxdb#6995

Revert "feat: db8 error handling"

---

docs-src/docs/cleanup.md

Fixed some grammatical errors
This PR contains:
IMPROVED DOCS: Cleanup
Describe the problem you have without this PR
Incorrect and difficult-to-understand grammar

Update(docs): Updated grammar in cleanup

---

CHANGELOG.md
package.json
src/plugins/validate-ajv/index.ts
test/unit/validate.test.ts

FIX #7253 Data format error in quickstart example

---

CHANGELOG.md
src/plugins/migration-schema/migration-helpers.ts
src/replication-protocol/default-conflict-handler.ts
src/replication-protocol/downstream.ts
src/types/rx-error.d.ts
test/unit/config.ts
test/unit/crdt.test.ts
test/unit/migration-schema.test.ts
test/unit/replication.test.ts
test/unit/rx-document.test.ts
test/unit/rx-query.test.ts
test/unit/rx-storage-query-correctness.test.ts

https://github.com/pubkey/rxdb/issues/7260
https://github.com/pubkey/rxdb/pull/7261

FIX #7260 updates not working after migration of replication state
